version: 2

build:
  image: latest

python:
  version: "3.6"

  # the following config does:
  #   $ pip install .[docs]
  #   $ python package/setup.py install
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: setuptools
      path: package

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false
