version: 2

python:
  # the following config does:
  #   $ pip install .[docs]
  #   $ python setup.py install
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: setuptools
      path: .

build:
  os: ubuntu-22.04
  tools:
    python: "3"

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false
